# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u9886\u57df\u540d')),
                ('keywords', models.CharField(max_length=500, null=True, verbose_name='\u5305\u542b\u54ea\u4e9b\u5173\u952e\u5b57')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Domain')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Page')),
            ],
        ),
    ]
