# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170627_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='has_birth_date',
            field=models.BooleanField(default=False),
        ),
    ]
