# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_page_has_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='death_data',
            new_name='death_date',
        ),
    ]
